export default [
    {
        id: '0',
        image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/1.jpg',
        type: 'Private Room',
        description: 'Lorem ipsum dolor sit amet. Sit iste dolore aut amet fugit qui excepturi eius qui dignissimos harum. Qui placeat molestiae et deserunt quia et excepturi harum ut alias quia hic temporibus dolorem. Ut quod sapiente ea excepturi aspernatur At ipsam dolor ut ipsam adipisci.Lorem ipsum dolor sit amet. Sit iste dolore aut amet fugit qui excepturi eius qui dignissimos harum. Qui placeat molestiae et deserunt quia et excepturi harum ut alias quia hic temporibus dolorem. Ut quod sapiente ea excepturi aspernatur At ipsam dolor ut ipsam adipisci.',
        title: 'Bright room in the heart of the city',
        bed: 2,
        bedroom: 3,
        oldPrice: 25,
        newPrice: 20,
        totalPrice: 120,
        coordinate: {
            latitude: 28.3915637,
            longitude: -16.6291304,
        },
        username: 'Müberra',
        email: 'muberra.catak45@gmail.com',
        lastname: 'Çatak'
    },
    {
        id: '1',
        image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/2.jpg',
        type: 'Entire Flat',
        description: 'Lorem ipsum dolor sit amet. Sit iste dolore aut amet fugit qui excepturi eius qui dignissimos harum. Qui placeat molestiae et deserunt quia et excepturi harum ut alias quia hic temporibus dolorem. Ut quod sapiente ea excepturi aspernatur At ipsam dolor ut ipsam adipisci.Lorem ipsum dolor sit amet. Sit iste dolore aut amet fugit qui excepturi eius qui dignissimos harum. Qui placeat molestiae et deserunt quia et excepturi harum ut alias quia hic temporibus dolorem. Ut quod sapiente ea excepturi aspernatur At ipsam dolor ut ipsam adipisci.',
        title: 'NEW lux. apartment in the center of Santa Cruz',
        bed: 3,
        bedroom: 2,
        oldPrice: 76,
        newPrice: 65,
        totalPrice: 390,
        coordinate: {
            latitude: 28.4815637,
            longitude: -16.2291304,
        },
        username: 'Tuğçe',
        email: 'tugcecatak@gmail.com',
        lastname: 'Çatak'
    },
    {
        id: '2',
        image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/3.jpg',
        type: 'Private Property',
        description: 'Lorem ipsum dolor sit amet. Sit iste dolore aut amet fugit qui excepturi eius qui dignissimos harum. Qui placeat molestiae et deserunt quia et excepturi harum ut alias quia hic temporibus dolorem. Ut quod sapiente ea excepturi aspernatur At ipsam dolor ut ipsam adipisci.Lorem ipsum dolor sit amet. Sit iste dolore aut amet fugit qui excepturi eius qui dignissimos harum. Qui placeat molestiae et deserunt quia et excepturi harum ut alias quia hic temporibus dolorem. Ut quod sapiente ea excepturi aspernatur At ipsam dolor ut ipsam adipisci.',
        title: 'Green House Santa Cruz',
        bed: 2,
        bedroom: 1,
        oldPrice: 64,
        newPrice: 55,
        totalPrice: 330,
        coordinate: {
            latitude: 28.2515637,
            longitude: -16.3991304,
        },
        username: 'Büşra',
        email: 'busracatak@gmail.com',
        lastname: 'Çatak'
    },
    {
        id: '3',
        image: 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/images/4.jpg',
        type: 'Entire Flat',
        description: 'Lorem ipsum dolor sit amet. Sit iste dolore aut amet fugit qui excepturi eius qui dignissimos harum. Qui placeat molestiae et deserunt quia et excepturi harum ut alias quia hic temporibus dolorem. Ut quod sapiente ea excepturi aspernatur At ipsam dolor ut ipsam adipisci.Lorem ipsum dolor sit amet. Sit iste dolore aut amet fugit qui excepturi eius qui dignissimos harum. Qui placeat molestiae et deserunt quia et excepturi harum ut alias quia hic temporibus dolorem. Ut quod sapiente ea excepturi aspernatur At ipsam dolor ut ipsam adipisci.',
        title: 'Typical canarian house',
        bed: 4,
        bedroom: 3,
        oldPrice: 120,
        newPrice: 100,
        totalPrice: 600,
        coordinate: {
            latitude: 28.4815637,
            longitude: -16.2991304,
        },
        username: 'Tubanur',
        email: 'tubanurcatak@gmail.com',
        lastname: 'Çatak'
    },
];
